"""empty message

Revision ID: ed27032ea991
Revises: 2474939bcb54
Create Date: 2022-02-25 04:18:27.224649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed27032ea991'
down_revision = '2474939bcb54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
