name: Build and deploy code

on: [push]

jobs:
  job1:
    runs-on: ubuntu-lastest
    steps:
      - name: git pull repo
        uses: actions/checkout@v2
      - name: say hello to kokoserver
        run: echo " hello kokoserver"

